### PR TITLE
Upstream/editsessionbuilder

### PR DESCRIPTION
**Pull request by aurorasmiles**
Implementing the EditSessionBuilder from upstream

### CODE REVIEW

**Comment by MattBDev** [comment]
As soon as anyone has time we need to continue work on this PR.

**Comment by dordsor21** [comment]
Should this be closed in favour of #1112 ?

**Comment by NotMyFault** [comment]
Likely, the work now happens #1112

**Comment by MattBDev** [comment]
Closed in favor of the continuing work in #1112

**Pull request closed without merging**
