### PR TITLE
feat: improve fawe limits (#2773)

### LINKED ISSUE #1874: Bad calculation of the number of blocks changed?
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

I have currently some problems with max-changed limitation.

I have a rank named 'builder-plus' with 8 millions max-change

```yaml
limits:
[some-line]
  builder-plus:
    # Max actions that can be run concurrently (i.e. commands)
    max-actions: 2
    # Max number of block changes (e.g. by `//set stone`).
    max-changes: 8000000
    # Max number of blocks checked (e.g. `//count stone` which doesn't change blocks)
    max-checks: 80000000
    # Number of times a change can fail (e.g. if the player can't access that region)
    max-fails: 4000000
    # Allowed brush iterations (e.g. `//brush smooth`)
    max-iterations: 500
[some-line]
```

But with `//pos1` `//pos2` and `//set stone` they are limited to 2.5 millions blocks.

I have checked, the permission is well configured, here exemple of luck perms record:
image

### To Reproduce

1. Define limitation
2. Check permission to be limited
3. Try the limitation with simple `//set stone`

### Expected behaviour

I suppose there are complicated to fix this kind of bug.

Many add some step into resolution of this bug : 
As add log or complete the error message with value compared (current max-changed of player and current selection count) ?

### Screenshots / Videos

image

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/6e996039991c46ef9176dc2941395c5c

### Fawe Version

FastAsyncWorldEdit-2.4.1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### LINKED ISSUE #2679: max-blockstates config limit is not enforced on //set
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

I have `max-blockstates: 5` however this restriction doesn't seem to be enforced when using `//set` or `//set #clipboard`.

Here is an example of where I was able to set 59,000 hoppers when it should have stopped me:
Example: //set hopper

### To Reproduce

1. Set max-blockstates: to a low number
2. Set a block entity beyond the limit you set

### Expected behaviour

WorldEdit action should be prevented

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a64ea766b59b41a796b4fb6fe87c1008

### Fawe Version

2.9.3-SNAPSHOT-724;ca2c18e

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- add FaweLimit implementations for increasing concurrency levels
 - allow FaweLimit to perform processing (and forcefully disable as required) to capture [tile] entities
 - Use `BlockVector3#set(Extent orDefault)` where appropriate to reduce block checks
 - fixes #2679
 - take 2 looks like it should work fine

### CODE REVIEW

**Comment by dordsor21** [comment]
See [dea1fcf](https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/2858/commits/dea1fcf7d838d0855010ae068e127797faa277cd) for fix

**Comment by SirYwell** [comment]
So, changing from `Extent#method(BV3)` to `BV3#method(Extent)` might skip the LimitExtent, but only when processing? If so, that's fine, and should bring a nice performance improvement in general for everything that reads from the world (some patterns, most masks).

I'm not sure about the different limit implementations. Are they needed? How relevant would be the overhead when just having a limit using `Atomic*` types? We could also probably use `VarHandle`s to have more control over memory ordering while also reducing objects needed in that case. Does the `ProcessorFaweLimit` actually improve performance? The lambda in `updateAndGet` might be called multiple times, while also writing to a volatile variable...

Similarly, the `SynchronousSettingExpected` annotation and the boolean flags feel a bit fragile and more like band-aid. Those are also only needed because of the different limits, right?

**Comment by dordsor21** [comment]
In fairness where we're likely to see the speed matter is concurrent-capable operations that are already fast, i.e. set and replace, where we'd be using the concurrent limit anyway so it's probably worth just collapsing to atomic.

I don't think VarHandles can offer us much more than we're getting with Atomic. We need to be sure of both the read and write at the same time and the read only matters "once" as the edit is consequently exited so I would say the simplicity of Atomic is worth it. The memory overhead is also next to nothing

**Review by SirYwell — APPROVED** [review]
Looks good. One thing I noticed is that `ABlockMask#test(Extent, BV3)` still goes through the extent. I wonder if we actually need that method at all or if the default is good enough, or if it is safe to go the `vector.getBlock(extent)` route there too. E.g. a `//replace stone diamond_block` on a 2048x320x2048 area takes ~26s vs ~17s due to that.

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
