### PR TITLE
refactor: Drop custom snakeyaml implementation

### PR DESCRIPTION
**Pull request by NotMyFault**
## Description
Our `YAML` class used to be a straight up copy from SnakeYAML. I can't tell what kind of purpose that used to serve, but we can safely remove it and rely on the methods provided at runtime.

## Submitter Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] I tested my changes and approved their functionality.
- [X] I ensured my changes do not break other parts of the code
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

## Maintainer checklist

Before the changes are marked as `Ready for merge`: 

- [ ] There are at least 2 approvals from project developers or maintainers for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [X] Changelog entries in the PR title are correct
- [X] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional modification steps from users, e.g. for permission changes, make sure the entry is added to the pull request description so it can be appended to the changelog.

### CODE REVIEW

**Comment by NotMyFault** [comment]
@dordsor21 Mind taking a look? Looks good so far imo, configs working still; I'd like to integrate that before next week.

**Comment by dordsor21** [comment]
The class being present in FAWE has nothing to do with comments or anything? Presumably new config file generation etc. works fine

**Comment by NotMyFault** [comment]
> Member

No, that works fine. Looking back in history, it was added in 2016. I could only imagine a scenario like Jesse wanted to use newer features but spigot bundling an outdated version? Or something else that got lost over the years.

**Review by dordsor21 — APPROVED** [review]

**Pull request merged**
