### PR TITLE
Avoid int overflow when using fillr in negative coords

### LINKED ISSUE #1667: "minY <= maxY required" when using /fillr below Y0 and no depth parameter is specified
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

The /fillr command breaks when using it below Y0.

```
[12:29:37 INFO]: Antlia issued server command: //fillr 1 100
[12:29:37 ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.lang.IllegalArgumentException: minY <= maxY required
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at com.sk89q.worldedit.function.mask.BoundedHeightMask.<init>(BoundedHeightMask.java:44) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.EditSession.fillXZ(EditSession.java:1465) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.command.UtilityCommands.fillr(UtilityCommands.java:331) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.command.UtilityCommandsRegistration.cmd$_fillr(UtilityCommandsRegistration.java:553) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:730) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:751) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:732) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:702) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

### To Reproduce

1. Go below Y0
2. /fillr 1 10

### Expected behaviour

No exception.

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/3b6551a68fdb415d9ea91a836d50a9e0

### Fawe Version

2.1.1-SNAPSHOT-133;05f80f2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- default to a depth of "radius"
 - Fixes #1667

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]
Untested, looks good

**Comment by SirYwell** [comment]
This should probably be upstreamed instead.

**Comment by dordsor21** [comment]
The upstream PR that would be cherry-picked here most likely https://github.com/EngineHub/WorldEdit/pull/2082

**Comment by dordsor21** [comment]
I've implemented the same fix being PRed to EH. Since that's still sitting there, we should probably go ahead and implement here anyway.

**Review by SirYwell — APPROVED** [review]
Guess we can integrate it for now.

**Pull request merged**
