### PR TITLE
fix regex and remove forbidden windows characters

### LINKED ISSUE #1872: Allowed filenames can be problematic with windows
### What feature do you want to see added?

Add a check if the filename is forbidden on windows, as it can be a problem when hosting on windows or letting users download those schematics. All forbidden filenames/characters on windows can be found here: https://stackoverflow.com/a/31976060

### Are there any alternatives?

no

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Xaver106**
## Overview

Fixes #1872

## Description

Just some refactoring of the regex

## Submitter Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Xaver106** [comment]
ok to test

**Comment by NotMyFault** [comment]
I have no access to a windows machine, could you provide an automatic test please, which verifies the desired result?

**Comment by Xaver106** [comment]
> I have no access to a windows machine, could you provide an automatic test please, which verifies the desired result?

This change is not Windows specific. It just modifies the filename verification to not allow windows speciific illegal characters.

**Comment by RedstoneFuture** [comment]
grafik
grafik

**Review by dordsor21 — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
Untested

**Pull request merged**
