### PR TITLE
Only send PacketPlayOutChunkMap for chunk updates

### PR DESCRIPTION
**Pull request by aurorasmiles**
Improves performance and fixes issues with PacketPlayOutChunkMap when using Spigot

### CODE REVIEW

**Review by dordsor21 — COMMENTED** [review]
Can this method only be used with 1.16? We should make the change to all adapters if not

**Comment by aurorasmiles** [comment]
> 
> 
> Can this method only be used with 1.16? We should make the change to all adapters if not

What method are you refering to? 1.16.2 changed a bit of NMS stuff, which is why we initially needed those changes for 1.16.2 in the first place

**Comment by dordsor21** [comment]
> > Can this method only be used with 1.16? We should make the change to all adapters if not
> 
> What method are you refering to? 1.16.2 changed a bit of NMS stuff, which is why we initially needed those changes for 1.16.2 in the first place

The one that you've switched to for sending chunk packets. Perhaps not necessarily a method change, but switching to the more performant method of sending updates only when needed should be done to all adapters if possible.

**Comment by IronApollo** [comment]
Does the crash happen for users of Spigot 1.16.1, 1.16, 1.15, etc? If it does, then the fix should likely be ported to the respective adapters. If it doesn't and users are not crashing on the Spigot platform on those versions, no port should be needed. This does need to be clarified before the PR is approved from my end!

Thanks for your work as always though :)

**Comment by aurorasmiles** [comment]
The crash is only on Spigot 1.16.2 because of the nms changes

**Review by IronApollo — APPROVED** [review]
If the issue only occurs on 1.16.2, this should be a finalized PR. Thanks again

**Comment by dordsor21** [comment]
If it's a performance boost/general correct way of doing it, then it should be on all versions. But okay.

**Pull request merged**
