### PR TITLE
fix(GriefDefender): invalidate mask on claim change

### LINKED ISSUE #2889: FastAsyncWorldEdit bypasses GriefDefender protection
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

When a player uses GriefDefender to create a claim, they then use FAWE to edit the claim. Delete the claim and players can still use FAWE operations in the area until the player rejoins.

I've stated this issue to the GriefDefender author, but he said it's a FAWE issue.

### To Reproduce

Create a claim and use FAWE to edit within the claim. Delete the claim and use FAWE to edit it.

### Expected behaviour

After deleting a claim, players should not be able to use FAWE to edit the area of ​​that claim (which has been deleted).

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/3c40e048757d4377a036c0c26e8b3ee3

### Fawe Version

2.11.2-SNAPSHOT-883;a64e09a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview
Fixes #2889

## Description
No idea if it works, ain't gonna pay 15 euros just for testing

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

**Comment by iiAhmedYT** [comment]
Whoever tests for 15euro, how did you manage that 😭 I WAN THAT TOO

**Comment by PierreSchwang** [comment]
> Whoever tests for 15euro, how did you manage that 😭 I WAN THAT TOO

uhm, what? what do you want too? lol

**Comment by iiAhmedYT** [comment]
the possibility of people accepting to pay 15eur just for a pr request

**Comment by PierreSchwang** [comment]
I don't want to pay 15 USD for GriefDefender to test this PR is what I meant haha
GitHub is not maintained anymore - so to test it, I'd have to buy GriefDefender, which I don't want to

**Comment by iiAhmedYT** [comment]
oh, i thought that was someone not a plugin 😭

**Review by SirYwell — APPROVED** [review]
That could work, maybe @TWME-TW can test the changes.

**Comment by TWME-TW** [comment]
> That could work, maybe @TWME-TW can test the changes.

Yes I can test it, I will test it on September 3rd

**Review by dordsor21 — APPROVED** [review]

**Comment by TWME-TW** [comment]
@PierreSchwang After testing, this PR successfully fixed the problem

**Comment by PierreSchwang** [comment]
Thank you for testing and validating!

**Pull request merged**
