### PR TITLE
feat: implement graceful world bounds check where appropriate

### LINKED ISSUE #2491: An unexpected error while handling a FastAsyncWorldEdit command java.lang.IllegalArgumentException: minY <= maxY required
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

The player is using the command incorrectly based on the log but it prints an error, is there a way to not print this error to console if the player used the command incorrectly?
```
[11:57:47] [Server thread/INFO]: PillowHealer974 issued server command: //fill stone 4
[11:57:47] [AsyncNotifyKeyedQueue - 20/ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.lang.IllegalArgumentException: minY <= maxY required
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at com.sk89q.worldedit.function.mask.BoundedHeightMask.<init>(BoundedHeightMask.java:44) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.EditSession.fillXZ(EditSession.java:1491) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.EditSession.fillDirection(EditSession.java:1420) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.command.UtilityCommands.fill(UtilityCommands.java:253) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.command.UtilityCommandsRegistration.cmd$_fill(UtilityCommandsRegistration.java:539) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:725) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:746) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:698) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```

### To Reproduce

1. Use //fill stone 4

### Expected behaviour

No error in console

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e0aa3c2b58744559ac6f4bcff0b2b087

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.8.2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### LINKED ISSUE #2494: java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

When this player joins the server this error is printed:
```
[09:42:01 INFO]: UUID of player yefreitor is f7c78a7c-f655-44e6-a40b-5ea36782c1f1
[09:42:01 WARN]: java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[09:42:01 WARN]:        at java.base/java.lang.String.checkIndex(String.java:4575)
[09:42:01 WARN]:        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:46)
[09:42:01 WARN]:        at java.base/java.lang.String.charAt(String.java:1535)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.world.entity.EntityTypes.convertEntityId(EntityTypes.java:472)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.world.entity.EntityTypes.parse(EntityTypes.java:481)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.entity.BaseEntity.<init>(BaseEntity.java:118)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.loadNBTFromFileFooter(DiskOptimizedClipboard.java:270)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:198)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:167)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.loadFromFile(DiskOptimizedClipboard.java:223)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.LocalSession.lambda$loadClipboardFromDisk$1(LocalSession.java:921)
[09:42:01 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150)
[09:42:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[09:42:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[09:42:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[09:42:01 INFO]: yefreitor[/*:54562] logged in with entity id 3161 at ([plotworld]-2090.565644499244, 68.49120751720224, -37060.77915434401)
```

### To Reproduce

1. Not sure

### Expected behaviour

No error in console

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d3dcbe34a5a2403cb2fe8a94deac18fc

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.8.2.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- closes #2491

### CODE REVIEW

**Comment by PierreSchwang** [comment]
Looks good so far - but how would that address the linked issue? The issue seems to be rather about a broken clipboard containing an entity with an empty id (`""`)

**Comment by dordsor21** [comment]
Ah sorry linked the wrong issue

**Review by PierreSchwang — APPROVED** [review]
The code looks good so far - makes sense.

Does this only affect the utility commands as the position is directly passed using the players positions? I guess all region based commands just use their internal positions which have to be in bounds?

**Comment by dordsor21** [comment]
> The code looks good so far - makes sense.
> 
> Does this only affect the utility commands as the position is directly passed using the players positions? I guess all region based commands just use their internal positions which have to be in bounds?

It's only where we're explicitly using `WorldEdit#checkExtentHeightBounds` as only a handful of commands would never use e.g. transforms

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
