### PR TITLE
use JavaPlugin.getResource() instead of JarFile.getEntry()

### PR DESCRIPTION
**Pull request by tsao-chi**
## Description

use JavaPlugin.getResource() instead of JarFile.getEntry()

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/blob/1.15/CONTRIBUTING.md)

### CODE REVIEW

**Comment by MattBDev** [comment]
Is there a reason for this change?

**Comment by tsao-chi** [comment]
`JavaPlugin.getResource()` is more readable and faster

**Comment by yannicklamprecht** [comment]
Also: No need to load/open a Jar twice if it is already loaded into ram. -> faster

**Comment by tsao-chi** [comment]
@SirYwell [upstream PR](https://github.com/EngineHub/WorldEdit/pull/566) was merged

**Pull request merged**
