### PR TITLE
Support using //distr on console properly

### LINKED ISSUE #1537: //distr fails to work on console.
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

The output of `//distr` when performed by console is blank.

```
[00:35:45] [ForkJoinPool-8-worker-14/INFO]: ------------- Block Distribution -------------
Total Block Count: 43088256
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  3               
  0.000%  3               
  0.000%  3               
  0.000%  3               
  0.000%  3               
  0.000%  3               
  0.000%  4               
  0.000%  4               
  0.000%  4               
  0.000%  4               
---------------- Page 2 of 10 ----------------
```

### To Reproduce

select a loaded region by a player using the console,
```
//world world
//pos1 165,165,165
//pos2 -165,165,-165
//expand vert
//distr
```

### Expected behaviour

expected that the console would dump the output to chat, unpaginated (since console), with blocks filled in.

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8f0b40fc6029476bb5b7b1d0eceecd1d

### Fawe Version

FastAsyncWorldEdit- 2.0.0-SNAPSHOT-47

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- Fixes #1537

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]
My zsh color theme is definitely not made for this

**Review by SirYwell — APPROVED** [review]

**Comment by dordsor21** [comment]
> My zsh color theme is definitely not made for this

What's it look like? o.o

**Comment by NotMyFault** [comment]
> > My zsh color theme is definitely not made for this
> 
> What's it look like? o.o

**Comment by dordsor21** [comment]
White on white huh?

**Comment by NotMyFault** [comment]
> White on white huh?

Somewhat of, just the console theme, zsh at IJ is fine :P

**Pull request merged**
