### PR TITLE
Fix `//regen -b` on 1.18.2

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Description
Fixes https://discord.com/channels/268444645527126017/344128526435221505/950410113687105606
`//regen -b` now works again, as the data type for the biome was casted wrong.

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] I tested my changes and approved their functionality.
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]
Works great, thanks

**Review by dordsor21 — APPROVED** [review]

**Review by SirYwell — CHANGES_REQUESTED** [review]
I think the `adapt` method is already wrong here. In previous adapters, it returns a WE `BiomeType`. It currently returns a `Holder<Biome>` from a `Holder<Biome>` instead. That doesn't look right to me...

**Comment by dordsor21** [comment]
> I think the `adapt` method is already wrong here. In previous adapters, it returns a WE `BiomeType`. It currently returns a `Holder<Biome>` from a `Holder<Biome>` instead. That doesn't look right to me...

This is true. The PR fixes the "wrong issue"

**Review by NotMyFault — APPROVED** [review]

**Review by SirYwell — APPROVED** [review]

**Comment by NotMyFault** [comment]
Skipping further review period due late fixup for 1.18.2

**Pull request merged**
