### PR TITLE
Create SurfaceAngleMask

### PR DESCRIPTION
**Pull request by josephjthomas**
## Description

I created a mask, which allows you to replace only the surface of blocks. You can use it with the following command `//replace #surfaceangle[min][max][depth] (material)`.
min, max and depth are ints, material is any valid material replacement.

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]
I gave it a try with the format provided and it worked as described. However, a similar behavior might can be achieved with a mask and excluding certain blocks, but I'm not opposed to a shorthand.

**Review by dordsor21 — APPROVED** [review]
lgtm

**Comment by JayemCeekay** [comment]
Hey, so this is actually code I wrote for Arcaniax's Arceon plugin. He literally just took the code and change #arcangle to #surfaceangle. Even the method names are the exact same.

**Comment by josephjthomas** [comment]
Hey, I bought the source code of your FAWE addon and came to the conclusion, that providing some of the mathematical formula used in masks and patterns could benefit people using FAWE and could be added directly to FAWE, as I think, they fit well into it.

**Comment by Brennian** [comment]
> Hey, I bought the source code of your FAWE addon and came to the conclusion, that providing some of the mathematical formula used in masks and patterns could benefit people using FAWE and could be added directly to FAWE, as I think, they fit well into it.

While I appreciate your support on my Arceon plugin, you claimed you created the mask by plagiarizing code specifically created for Arceon by JayemCeekay. The source you can request for Arceon does not mean you can just submit it publicly, I personally thought it was pretty logical that it is not a ethical thing to do. You can however modify Arceon on your own servers with the source code if you do wish to do so.

**Comment by josephjthomas** [comment]
> While I appreciate your support on my Arceon plugin, you claimed you created the mask by plagiarizing code specifically created for Arceon by JayemCeekay.

I don't make any claims that the modified code belongs to me. I used the term "created" in form of an alias for "added", or "appended". I admit it sounds misleading if you read it and I apologize for any confusion it caused.
> The source you can request for Arceon does not mean you can just submit it publicly

The Bukkit project is licensed under GPL, therefore any plugin must be GPL compliant too. So according the lines of GPL
- "You may copy and distribute verbatim copies of the Program's source code as you receive it, in any medium"
- "You may modify your copy or copies of the Program or any portion of it, thus forming a work based on the Program, and copy and distribute such modifications or work"

You sent me a copy of the code I modified and submitted my code modifications while respecting the GPL license.

> I personally thought it was pretty logical that it is not an ethical thing to do

You violated the Bukkit (inherited the FAWE and WorldEdit) license by not disclosing your code or shipping a copy of GPL within your plugin. I'm surprised that you call my work unethical and illogical, because I acted within the permission of the license.

**Pull request merged**
