### PR TITLE
fix: Improve edit processing

### LINKED ISSUE #1861: Undo of big pastes does not remove all blocks
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

The //undo for big structures does not seem to remove all the blocks pasted.

### To Reproduce

1. Copy a big amount of blocks
2. Paste it somewhere ( for example in the sky or in the void )
3. Undo
4. You should see blocks flying around

### Expected behaviour

Clear all the blocks pasted.

### Screenshots / Videos

https://www.youtube.com/watch?v=POocbUssI9s

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1245dfd6feb14454a9f6596869f929f3

### Fawe Version

FastAsyncWorldEdit version 2.4.1-SNAPSHOT-237;dbfb521

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Actually my build isn't the newest but the last two were updates of paperweight and some docs modifications as far as i see.

### LINKED ISSUE #2074: Error | Chunk Queue Skipping
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

After replacing a semi-large section (roughly half a million blocks) with a not too simple gmask (|!#solid), some chunks will be skipped during the replacement process. This could end up with some chunks replacing too many blocks, as it treats the surrounding chunks as full air, or no blocks at all if it's a chunk that is being skipped.

Sometimes undoing it wont even restore some chunks, leaving us with no other choice but to re-import the entire world or manually fixing the terrain ourselves.

We are as of now 8 builds behind (336 instead of 344) and none of the later builds mention anything related to chunk loading/queues being resolved.

### To Reproduce

1. use //gmask "|!#solid" to mask anything next to non-solid blocks (water and air)
2. select 2 positions of a mountain with different block types (roughly 500k blocks and 7 different block types)
3. use //replace slot1,slot2,slot3,slot4,slot5,slot6,slot7 air to replace these 7 block types with air. This should make the mountain 1 block thinner
4. use //replace slot3,slot4,slot5,slot6,slot7 air to replace fewer block types with air. This should make parts of the mountain 1 block thinner
5. the command can be performed multiple times up until the error starts to occur. Sometimes undoing it will also stop working for some chunks.

### Expected behaviour

All chunks will be replaced and none should be skipped or treated as air

### Screenshots / Videos

image
image
In this image you can see there is one big flat wall that did not get removed, as it skipped that chunk the 2nd time the command was performed. In the 2nd image you can see if being in a separate chunk than the blocks on the left side.

image
In this image we were unable to undo the actions in the middle 2 chunks. the chunk all the way to the left and right were able to be undone successfully.

### Error log (if applicable)

https://pastebin.com/BzWD8Ub2

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2a2e01321b364e10911163b80ed92e75

### Fawe Version

FAWE version 2.5.1-Snapshot-336

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
Create a copy of SET chunk before processing
 - Completely nullifies issue of writing to SET between processing submission and processing completion
 - Leads to larger memory footprint, but that is acceptable
 - Leads to performance improvement in processing as there is no need to perform any multi-threading protection operations
 - Fixes #1861
 - Fixes #2074 (gonna go ahead and say it does, this is really the only thing I can think of to do with the issue, and it's super rare anyway (never replicated by anyone else))## Overview
 - *tack on some changes (increased default/recommended target size)
 - *tack on some changes (minor cleanup)
 - *tack on some changes (improve a couple of CharSetBlocks methods)

### CODE REVIEW

**Comment by SirYwell** [comment]
This has some conflicts with #2181

**Comment by MattBDev** [comment]
> Leads to larger memory footprint, but that is acceptable.
I know our memory usage is already pretty good and can take a hit but I am curious as to how much more memory this uses. Did you have an estimate?

**Comment by dordsor21** [comment]
> > Leads to larger memory footprint, but that is acceptable.
> > I know our memory usage is already pretty good and can take a hit but I am curious as to how much more memory this uses. Did you have an estimate?

0.5 to maybe 4 Mbit a chunk I guess (so 0.1 to 0.5 MB)

**Review by MattBDev — APPROVED** [review]

**Review by SirYwell — CHANGES_REQUESTED** [review]
found a typo but looks good otherwise

**Review by SirYwell — APPROVED** [review]

**Pull request merged**
