### PR TITLE
fix: fix plot swap

### LINKED ISSUE #2076: Swapping plots does not work with FAWE
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

/p swap does not work.
I wanted to swap plot 1;-1 with plot 0;-1.
Plot 1:-1 was copied to plot 0;1.

### To Reproduce

236 / 5.000
Übersetzungsergebnisse
Übersetzung
/p swap does not work.
I wanted to swap plot 1;-1 with plot 0;-1.
I was on plot 0;-1 and typed /p swap 1;-1
Plot 1:-1 was copied to plot 0;1.

### Expected behaviour

Plots 1;-1 and 0;-1 should be swapped.

### Screenshots / Videos

_No response_

### Error log (if applicable)

No error

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/26be28aa2eb54b9999b521986497e0cd

### PlotSquared Version

PlotSquared-Bukkit-7.0.0-SNAPSHOT.jar

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- deprecate and note for internal use only Clipboard#create as it's funky
 - fixes #2076

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
Conflicts

**Comment by OneLiteFeather** [comment]
Still conflicting?

**Comment by dordsor21** [comment]
Fixed

**Comment by OneLiteFeather** [comment]
Awesome! That is a feature many people are hoping for :)

**Review by NotMyFault — APPROVED** [review]

**Review by PierreSchwang — APPROVED** [review]

**Pull request merged**
