### PR TITLE
feat: re-submit chunk load request after 10s after checking world is loaded

### PR DESCRIPTION
**Pull request by dordsor21**
- #2332 makes it seem like paper forgets to load a chunk sometimes
 - resubmit chunk load request after a second to attempt to counter this

### CODE REVIEW

**Review by NotMyFault — DISMISSED** [review]

**Comment by SirYwell** [comment]
This doesn't resubmit anything, no? It's basically just  *wait one second for the future to complete, if completed return, otherwise wait for the same future to complete without timeout*.

I also think if that's actually an issue with paper, this should be fixed in paper (or, if we use something wrong here, we should use it right).

**Comment by dordsor21** [comment]
Unsure really, but the thread dump in the issue doesn't list any threads doing anything to do with chunk loading. It _does_ seem to be on Folia though, so I don't know if that might have anything to do with it?

**Comment by SecretlyJealous** [comment]
I'm not using folia I'm using paper 1.20.1, it's weird that the thread dump mentions folia though?

**Comment by SirYwell** [comment]
> I'm not using folia I'm using paper 1.20.1, it's weird that the thread dump mentions folia though?

It might come from a plugin which just uses suboptimal naming for threads. It might be worth to track that down and report it to the developer.

**Review by SirYwell — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
