### PR TITLE
[1.17.1] Native Adapter improvements

### PR DESCRIPTION
**Pull request by TheMeinerLP**
## Overview
This PR improve readability, error handling and code consistency. 

## Description

```[tasklist]
### Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

**Comment by NotMyFault** [comment]
Upstream structure changes should ultimately be PRed to upstream.

**Comment by TheMeinerLP** [comment]
> Upstream structure changes should ultimately be PRed to upstream.

Some instruction how can easily do that ? 
I had also planned for 1.18.2-1.20.2

**Comment by NotMyFault** [comment]
Ask upstream whether they are interested in such a change. If they aren't, we likely won't accept it either, to keep the maintenance diff as small as possible, especially for upstream classes.

**Comment by TheMeinerLP** [comment]
Will not be accepted at all.

**Pull request closed without merging**
