### PR TITLE
Several fixes to actual, probable and possible synchronocity issues

### PR DESCRIPTION
**Pull request by dordsor21**
- Ensure that all edits are queued onto the same AsyncNotifyQueue by actually delegating to the parent player in PlayerProxy
 - Ensure that the order editsessions are being remembered on the LocalSession is being respected by using a fair ReentrentLock

### CODE REVIEW

**Comment by dordsor21** [comment]
This will also fix some interesting history behaviour from #658 as we were editing too quickly... (lol)

**Comment by SirYwell** [comment]
http://haste.athion.net/obepumedaq.rb 
I got this deadlock when simply using a height brush.
send-before-history is set to true if that matters

**Comment by dordsor21** [comment]
> http://haste.athion.net/obepumedaq.rb
> I got this deadlock when simply using a height brush.
> send-before-history is set to true if that matters

Interesting... I tried a bunch of stuff but didn't get a lock. The change was the "possible" one so I've just undone it.

**Review by SirYwell — APPROVED** [review]
Seems to work now

**Review by N0tMyFaultOG — APPROVED** [review]

**Pull request merged**
