### PR TITLE
Avoid deprecated CompoundTag in API

### PR DESCRIPTION
**Pull request by SirYwell**
## Description

`CompoundTag` is deprecated and its implementation is now backed by `LinCompoundTag`. This causes significant overhead when access its data due to the needed transformation/copy.

This PR aims to address spots where `CompoundTag` is used in FAWE api, as well as some uses that can benefit from the reduced overhead. There is more to do to get `CompoundTag` fully out of FAWE, but more changes can be addressed later.

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]

**Comment by dordsor21** [comment]
Was moving to jetbrains annotations from javax done on purpose? I believe we're relatively consistent for the latter

**Comment by NotMyFault** [comment]
> Was moving to jetbrains annotations from javax done on purpose? I believe we're relatively consistent for the latter

JavaX is superseded by Jakarta. A migration away from JavaX is a good choice, whether it's its successor or a replacement.

**Comment by dordsor21** [comment]
> > Was moving to jetbrains annotations from javax done on purpose? I believe we're relatively consistent for the latter
> 
> JavaX is superseded by Jakarta. A migration away from JavaX is a good choice, whether it's its successor or a replacement.

Should probably make a decision and move all of them at once imo

**Comment by SirYwell** [comment]
> Was moving to jetbrains annotations from javax done on purpose? I believe we're relatively consistent for the latter

No, it's mostly because IntelliJ likes to use its annotations by default. I switched to javax for now, but we might want to consider switching to jspecify or checkerframework in future.

**Review by dordsor21 — APPROVED** [review]

**Pull request merged**
