### PR TITLE
Update worldedit-adapters.jar

### PR DESCRIPTION
**Pull request by N0tMyFaultOG**
https://github.com/IntellectualSites/worldedit-adapters/commit/b3fb88df1c59192ca8310b8b79078714396f63f6

### CODE REVIEW

**Comment by MattBDev** [comment]
This needs to be tested because I believe that the newest worldedit-adapters.jar is incompatible with FAWE right now.

**Review by aurorasmiles — APPROVED** [review]
Compiled it and tested the basic functions, everything seems to work fine. Altough I'm not exactly sure what was changed, nothing seems immediately broken

**Comment by N0tMyFaultOG** [comment]
> This needs to be tested because I believe that the newest worldedit-adapters.jar is incompatible with FAWE right now.

It is tested, what makes you thinking that my cherry-pick is incompatible with FAWE? It refers to Spigot shenanigans.

**Comment by MattBDev** [comment]
@N0tMyFaultOG I ran into several compiling errors with the new regeneration code that isn't implemented yet.

**Comment by N0tMyFaultOG** [comment]
> @N0tMyFaultOG I ran into several compiling errors with the new regeneration code that isn't implemented yet (when I tried doing this myself). If whatever you did works then that's great.

Compiling works perfectly fine for aurora and me 👀

**Comment by aurorasmiles** [comment]
To be fair I've started implementing the regen stuff and I'm not sure if the checkout stashes those changes, so that could be the reason it compiles for me

**Comment by N0tMyFaultOG** [comment]
> To be fair I've started implementing the regen stuff and I'm not sure if the checkout stashes those changes, so that could be the reason it compiles for me

Checkout allows you switching between branches only :P 
However, since it worked for me and GH actions - which is always a clean environment - I can assure compilation works fine.

**Comment by N0tMyFaultOG** [comment]
Thanks.

**Pull request merged**
