### PR TITLE
Show # of affected blocks in //set command

### LINKED ISSUE #1702: Show number of affected blocks in //set like legacy did
### What feature do you want to see added?

In the past, legacy had a feature where it showed the number of affected blocks when a user did `//set`. This feature is no longer in modern FAWE. 

### Are there any alternatives?

I've tried adding the `{0}` to the end of the string to see if it was internally passed. But it wasn't.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Orlaando-dev**
## Overview
Essentially legacy had a feature where users could see the number of affected blocks when doing //set. This feature is no longer present in FAWE. This PR aims to address and add this feature. Note that I didn't add the needed `{0}` to `strings.json` for the affected blocks to be actually shown, but again all the internal logic required to make it work has been added to this PR.

Fixes #1702 

## Description

Basically I just passed the # of affected blocks from the edit session to the caption. Once again, this was a feature on legacy and was removed for whatever reason?
## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] I tested my changes and approved their functionality.
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by NotMyFault** [comment]
@intellectualsites-bot retest this please

**Review by NotMyFault — COMMENTED** [review]
> Note that I didn't add the needed {0} to strings.json for the affected blocks to be actually shown, 

Any objections why you didn't add it here? I don't expect anyone to be aware of it if we don't ship it by default.

**Comment by dordsor21** [comment]
Agree with nmf that this should be inserted into existing strings

**Review by NotMyFault — APPROVED** [review]
Addressed my concerns

**Pull request merged**
