### PR TITLE
fix: ensure config-legacy.yml is created before accessed

### LINKED ISSUE #2742: NoSuchFileException when generating new config files (fresh setup)
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

All warns (see the Error log)

### To Reproduce

Start only the server with paper-1.20.4-496.jar downloadable from [here](https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/496/downloads/paper-1.20.4-496.jar).

### Expected behaviour

No warn at all, if possible

### Screenshots / Videos

_No response_

### Error log (if applicable)

https://gist.github.com/Nick31629/a07fd500a17715cd1fbaad6c390821ac

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/820b8f643aab4835b86a890bd994569a

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-776

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- fixes #2742

### CODE REVIEW

**Comment by dordsor21** [comment]
Still get an error due to FAWE config, but the config(s) are still created
```
[13:34:24 WARN]: java.nio.file.NoSuchFileException: plugins\FastAsyncWorldEdit\config.yml
[13:34:24 WARN]:        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[13:34:24 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[13:34:24 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[13:34:24 WARN]:        at java.base/sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:108)
[13:34:24 WARN]:        at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:282)
[13:34:24 WARN]:        at java.base/java.nio.file.Files.copy(Files.java:1304)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:67)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.configuration.Config.load(Config.java:104)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.configuration.Settings.reload(Settings.java:102)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.Fawe.setupConfigs(Fawe.java:349)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.Fawe.<init>(Fawe.java:107)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.Fawe.set(Fawe.java:197)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.bukkit.FaweBukkit.<init>(FaweBukkit.java:70)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:196)
[13:34:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[13:34:24 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[13:34:24 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[13:34:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[13:34:24 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639)
[13:34:24 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550)
[13:34:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:275)
[13:34:24 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[13:34:24 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[13:34:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[13:34:24 WARN]: java.io.FileNotFoundException: plugins\FastAsyncWorldEdit\config.yml (The system cannot find the file specified)
[13:34:24 WARN]:        at java.base/java.io.FileInputStream.open0(Native Method)
[13:34:24 WARN]:        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
[13:34:24 WARN]:        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.configuration.file.FileConfiguration.load(FileConfiguration.java:122)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:58)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.configuration.Config.load(Config.java:104)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.configuration.Settings.reload(Settings.java:102)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.Fawe.setupConfigs(Fawe.java:349)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.Fawe.<init>(Fawe.java:107)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.core.Fawe.set(Fawe.java:197)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.fastasyncworldedit.bukkit.FaweBukkit.<init>(FaweBukkit.java:70)
[13:34:24 WARN]:        at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:196)
[13:34:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[13:34:24 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[13:34:24 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[13:34:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[13:34:24 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639)
[13:34:24 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550)
[13:34:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:275)
[13:34:24 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[13:34:24 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[13:34:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Review by NotMyFault — APPROVED** [review]

**Comment by SirYwell** [comment]
> Still get an error due to FAWE config, but the config(s) are still created

Does that happen on a fresh setup? Might not be a great look in that case

**Comment by dordsor21** [comment]
> > Still get an error due to FAWE config, but the config(s) are still created
> 
> Does that happen on a fresh setup? Might not be a great look in that case

I can't remember if I was deleting the entire folder or just the config files, but in essence yes it does.

**Comment by dordsor21** [comment]
(fully fixed now)

**Review by SirYwell — APPROVED** [review]

**Pull request merged**
