### PR TITLE
Update to 1.20

### PR DESCRIPTION
**Pull request by NotMyFault**
TODO:
- [x] Address `net.minecraft.world.level.material.Material` removal
- [x] Address `LevelChunkSection` changes in `PaperweightPlatformAdapter`
- [x] Refractions
- [x] Regen
- [x] Update bom profile `bom-newest` in https://github.com/IntellectualSites/bom/blob/main/bom-newest/build.gradle.kts matching changes like snakeyaml 2.0

Help wanted!

### CODE REVIEW

**Comment by SirYwell** [comment]
<https://github.com/EngineHub/WorldEdit/commit/6bbcf74655d4fd32ada466a98f6c24689fa55d7e> is missing, therefore we currently have commented-out code in PaperweightAdapter. I think this is something we should address separately though.

**Comment by NotMyFault** [comment]
Testing on 1.20, 3781-Spigot-16cfc98-fd92f1e revealed the following issues so far:
- Screenshot 2023-06-09 at 09 32 21
Creating a schematic of this demo area via `//copy -e` -> `//schem save demo` -> `//paste -e` doesn't paste the armor stand. Chest content is stored properly.
What we get is:
Screenshot 2023-06-09 at 09 34 19
- `//chunk` -> `//set 0` -> `//undo` -> `//redo` ends up in a chunk with messed up lighting.
- Undoing a amount of edits across sessions or server reboots fires
```
[09:37:20] [Server thread/INFO]: PlotSquared issued server command: //undo 50
[09:37:20] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightPlatformAdapter.SERVER_LEVEL_ENTITY_MANAGER" is null
[09:37:20] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightPlatformAdapter.getEntities(PaperweightPlatformAdapter.java:670)
[09:37:20] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightGetBlocks.lambda$call$3(PaperweightGetBlocks.java:639)
[09:37:20] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightGetBlocks.lambda$call$7(PaperweightGetBlocks.java:786)
[09:37:20] [Server thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[09:37:20] [Server thread/WARN]: 	at com.fastasyncworldedit.core.queue.implementation.QueueHandler.operate(QueueHandler.java:160)
[09:37:20] [Server thread/WARN]: 	at com.fastasyncworldedit.core.queue.implementation.QueueHandler.run(QueueHandler.java:107)
[09:37:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82)
[09:37:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[09:37:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1257)
[09:37:20] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388)
[09:37:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198)
[09:37:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015)
[09:37:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[09:37:20] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[09:37:20] [AsyncNotifyQueue - 0/ERROR]: Catching
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightPlatformAdapter.SERVER_LEVEL_ENTITY_MANAGER" is null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.iterateSubmissions(SingleThreadQueueExtent.java:427) ~[?:?]
	at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:375) ~[?:?]
	at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.flush(SingleThreadQueueExtent.java:472) ~[?:?]
	at com.fastasyncworldedit.core.queue.IQueueExtent.commit(IQueueExtent.java:104) ~[?:?]
	at com.fastasyncworldedit.core.extent.PassthroughExtent.commit(PassthroughExtent.java:221) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:159) ~[?:?]
	at com.fastasyncworldedit.core.extent.PassthroughExtent.commit(PassthroughExtent.java:221) ~[?:?]
	at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1275) ~[?:?]
	at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:1156) ~[?:?]
	at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:611) ~[?:?]
	at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:90) ~[?:?]
	at com.sk89q.worldedit.command.HistoryCommandsRegistration.cmd$undo(HistoryCommandsRegistration.java:146) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:725) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:746) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:727) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:698) ~[?:?]
	at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[?:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:39) ~[?:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:56) ~[?:?]
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1456) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightPlatformAdapter.SERVER_LEVEL_ENTITY_MANAGER" is null
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightPlatformAdapter.getEntities(PaperweightPlatformAdapter.java:670) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightGetBlocks.lambda$call$3(PaperweightGetBlocks.java:639) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightGetBlocks.lambda$call$7(PaperweightGetBlocks.java:786) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at com.fastasyncworldedit.core.queue.implementation.QueueHandler.operate(QueueHandler.java:160) ~[?:?]
	at com.fastasyncworldedit.core.queue.implementation.QueueHandler.run(QueueHandler.java:107) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3781-Spigot-16cfc98-fd92f1e]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3781-Spigot-16cfc98-fd92f1e]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1257) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3781-Spigot-16cfc98-fd92f1e]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3781-Spigot-16cfc98-fd92f1e]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3781-Spigot-16cfc98-fd92f1e]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3781-Spigot-16cfc98-fd92f1e]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3781-Spigot-16cfc98-fd92f1e]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

I have ticked a few points on the checklist, assuming they're done. Correct me if I'm wrong please.

**Comment by SirYwell** [comment]
> Testing on 1.20, 3781-Spigot-16cfc98-fd92f1e revealed the following issues so far:

This is interesting as I think it fails on previous versions too. My latest commit should fix it for 1.20 though.

**Comment by NotMyFault** [comment]
I can't replicate the lighting stuff on Paper, therefore non-blocking.

**Pull request merged**
