### PR TITLE
Fix recursivePickaxe

### LINKED ISSUE #436: Area superpickaxe does not differentiate between block type - deletes it all
**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/6f1125d1f29242e98ce5b1dedf7120ca

**FastAsyncWorldEdit Version Number:** 
1.15-192;5fb1825

**Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-229 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Description of the problem:**
The area superpickaxe  (example: _/sp area 4_) should delete all blocks of the same type in the specified radius.
Now it simply deletes all blocks in the given radius.
It would be cool if you could restore the function this pickaxe had for years. Removing only the blocks of one type is much more useful than simply deleting all blocks.

**How to replicate**:
1. /sp area 4
2. left click
3. All blocks in the area get removed instead of all blocks of the block type one left clicked.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

### PR DESCRIPTION
**Pull request by aurorasmiles**
## Overview

**Fixes #436 again**

## Description
actually use the recurse function and not just delete everything in range
## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/blob/1.15/CONTRIBUTING.md)

### CODE REVIEW

**Comment by aurorasmiles** [comment]
I mean why it isn't working seems kinda obvious, because it just does nothing as far as I can tell.
I completely agree that we should find the root cause for this issue - but this PR would just be an easy fix to get it working again

**Comment by dordsor21** [comment]
Presumably, tested and works?

**Comment by aurorasmiles** [comment]
Yes, but I have no idea about performance with big radii

**Comment by TheoRetisch1** [comment]
The maximum radius is defined in the legacy-config to a default value of 5 blocks anyway + a radius of more than 20 blocks doesn't help at all with the purpose of the tool. So I guess, you don't have to worry about performance.

**Comment by dordsor21** [comment]
See #490

**Pull request closed without merging**
