### PR TITLE
Remove weak reference and replace with a simple not equal

### LINKED ISSUE #2188: Invalid region mask: PlotSquaredMask (unnecessary/slightly spammy message)
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

After updating from FAWE 2.6.0 to 2.6.1 players on my server complained about an error appearing in chat every time they use a worldedit command. The operation still works but it gives an error in chat, also the first operation does not give this error but any operation after that will give the error.

First operation gives no error:

Every operation after the first gives this error in chat "Invalid region mask: PlotSquaredMask":

### To Reproduce

1. Make sure you are not OP
2. Select a region with the wand and do `//set 0`
3. Do `//set stone` on the same region and you will get an error in chat

### Expected behaviour

There should be no error in chat

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/487f28fdfaa74188acd4ba24a4a22ecd

### Fawe Version

FastAsyncWorldEdit version 2.6.2-SNAPSHOT-408;9f3c909

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by TheMeinerLP**
## Overview
Fixes #2188 

## Description
Since 2.6.1 added some issue for plot squared mask with unlinked plot mask. Now without weak reference the code work again as expected.
Side information. I tested it locally

## Submitter Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PierreSchwang** [comment]
Have you tested, that the change does not break the recently implemented behavior? https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/e4158ac08401c293f98fe5ce85b7a64a1d299aef

**Comment by TheMeinerLP** [comment]
I have tested with P2

**Comment by SirYwell** [comment]
I don't see how this changes the actual behavior other than potentionally creating a memory leak. How is the weak ref the issue here?

**Comment by TheMeinerLP** [comment]
Before everytime there was a message on Fawe for the wea mask from p2 this prevents now the exception and fixes the linked issue. A weak reference is here not needed

**Comment by SirYwell** [comment]
The weak ref is used to avoid memory leaks, and I don't see the semantic difference here. That's why I'd like to know *how* this change fixes the issue.

**Comment by TheMeinerLP** [comment]
The hashset what we get is a strong one. Also in there original get logic from connected plots is a cache implemented. When we now use a weak reference the content gets never updated or to late.

**Comment by SirYwell** [comment]
The behavior of the contents doesn't change here, we call the getConnectedPlots method at the exact same places. The only difference is that if the cache is invalidated by PlotSquared, this solution still holds a strong reference to the *outdated* set that would otherwise be garbage collected with the existing solution.

**Comment by dordsor21** [comment]
It's actually a bug that the message _wouldn't_ show (i.e. the message showing is correct - the weak reference has done its job). That implies that the mask has been invalidated by FAWE, and thus recalculated. Perhaps the message isn't needed and would server better as a debug-related message.

**Comment by TheMeinerLP** [comment]
Okay for that i will replace it with your original code and replace the message with simple `logger.debug(FILLER)` ?
Thats right

**Comment by dordsor21** [comment]
> Okay for that i will replace it with your original code and replace the message with simple `logger.debug(FILLER)` ? Thats right

Not sure if we do it elsewhere, but the message would be more suited to sending to the player still

**Comment by TheMeinerLP** [comment]
I prefer to do that better in the future. Then my suggestion. Let switch to debug logging for like that

**Comment by dordsor21** [comment]
Closing in favour of #2238 and IntellectualSites/PlotSquared#4046

**Pull request closed without merging**
