### PR TITLE
feat: implement 1.21

### PR DESCRIPTION
**Pull request by dordsor21**
- support for Paper's new chunk gen system is out of scope for this PR

### CODE REVIEW

**Comment by dordsor21** [comment]
Propose keeping 1.20 minor versions due to the very high usage of 1.20.2 and 1.20.4 still
image

**Comment by dordsor21** [comment]
(Still untested)
(Haven't look at any of the refractions properly)

**Comment by dordsor21** [comment]
(regen is probably broken due to large changes)

**Comment by PierreSchwang** [comment]
> (Still untested) (Haven't look at any of the refractions properly)

Just one field updated, the remaining fields are identical.

**Comment by dordsor21** [comment]
Editing seems to work, including copying chests with contents. Regen as expected, does not work

**Comment by PierreSchwang** [comment]
> Editing seems to work, including copying chests with contents. Regen as expected, does not work

Do you want to push the PROPERTY_CACHE change into 1.21? Just did it locally for FAWE to work for me

**Review by NotMyFault — APPROVED** [review]

**Review by PierreSchwang — APPROVED** [review]
My previous tests on Paper showed no issues.

**Pull request merged**
