### PR TITLE
Remove temporary removes of workflow run event dispatch

### PR DESCRIPTION
**Pull request by TheMeinerLP**
## Description
There is current a issue with forked repositories when someone pushes into there repository.
Everytime is a action running. Thats makes github app spammy on your mobile device. 
image

## Submitter Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NotMyFault** [comment]
That is not correct. The workflow should remain disabled.

**Comment by TheMeinerLP** [comment]
Some reason why ?
I mean i got 10 or 50 push notifications on my repo about this workflow

**Comment by NotMyFault** [comment]
> Some reason why ?

The workflow release tag reference doesn't resolve and leads to invalid links sent to discord. Until this is resolved, the workflow remains disabled.

**Comment by TheMeinerLP** [comment]
You mean this one ?
```
https://github.com/IntellectualSites/FastAsyncWorldEdit/releases/tag/${{ github.event.release.tag_name }}
```

**Comment by NotMyFault** [comment]
Yes. Contrary to the FAVS workflow, the tag is handled different here, causing the plain text to be sent.

**Comment by TheMeinerLP** [comment]
When i can fix that for you. Then we can merge this ?

**Pull request closed without merging**
