### PR TITLE
Fix PSv4 config error

### PR DESCRIPTION
**Pull request by NotMyFault**
## Description
Fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1372

## Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] I tested my changes and approved their functionality.
- [X] I ensured my changes do not break other parts of the code
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by dordsor21** [comment]
Any particular reason for not using debug? I feel it would fit better here

**Review by dordsor21 — APPROVED** [review]

**Comment by SirYwell** [comment]
Is there any specific reason why we don't just make the `v` uppercase here https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/2c56e480c3a4171d71c71103e965ae4f376fb368/worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java#L91?

**Comment by NotMyFault** [comment]
> Is there any specific reason why we don't just make the `v` uppercase here
> 
> https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/2c56e480c3a4171d71c71103e965ae4f376fb368/worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java#L91
> 
> ?

Considering it's already marked for removal, I spend no further time with its implementation. Although, _my_ preferred solution would be dropping v4, since we dropped v5 when v6 arrived. Furthermore, the versions v4 supports no longer match with the versions Fawe supports.

**Comment by SirYwell** [comment]
> Considering it's already marked for removal, I spend no further time with its implementation.

I guess it would make more sense removing it althogether rather than spending time on it with workarounds.

**Comment by NotMyFault** [comment]
> > Considering it's already marked for removal, I spend no further time with its implementation.
> 
> I guess it would make more sense removing it althogether rather than spending time on it with workarounds.

If I remember correctly, @dordsor21 had some concerns about removing it, the last time we were debating about it.

**Comment by dordsor21** [comment]
If changing v4 -> V4 actually fixes the issue, this is trivial. V4 support currently requires not extra effort as it's working as-is, and _can_ still be used with FAWE. No need to remove v4 support until there's no way to run the two together.

**Comment by NotMyFault** [comment]
v4 used tp support 1.13 and 1.14, Fawe does no longer support these versions, so even if you are using v4, you can't use Fawe with it in the first place.

**Comment by dordsor21** [comment]
Does v4 not work at all with 1.15/16? I see no reason why it shouldn't work?

**Comment by NotMyFault** [comment]
I never gave it a try, as that used to be the time we dropped v5.

**Comment by dordsor21** [comment]
Looking at v4 reviews from entitlee people on spigot, it doesn't work on 1.16 but does on 1.15

**Comment by NotMyFault** [comment]
Oic, we have no overlapping statistic for that specific use case, but people using 1.15.2 are a small minority.

**Comment by dordsor21** [comment]
Title no longer fits

**Comment by NotMyFault** [comment]
> Title no longer fits

Smh, that only applies to repos using release drafter.

**Comment by NotMyFault** [comment]
Rebasing on Jenkins was successful.

**Comment by NotMyFault** [comment]
@SirYwell Named recommendation has been applied.

**Review by SirYwell — APPROVED** [review]
Looks good

**Pull request merged**
