### PR TITLE
Fixes unsafe memory access using cross server clipboards

### LINKED ISSUE #638: Unsafe memory access using cross server clipboards
# Bug report for FastAsyncWorldEdit 1.16.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/4688e1f451a5435da8a2ee16a417e391

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

```
[20:44:09 INFO]: FastAsyncWorldEdit-371 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
[20:44:09 INFO]: FAWE version:
- Date Sep 19, 2020 12:00:00 AM
- Commit f41f1cc9
- Build 371
- Platform Bukkit
[20:44:09 INFO]: Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
[20:44:09 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.16-371;be0e337)
[20:44:09 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 

git-Paper-202

**[REQUIRED] Description of the problem:**

If you paste something with ``//paste -a`` from one server to another an error gets thrown and FAWE pastes nothing. The servers uses a shared clipboard folder.

**How to replicate**:

Setup a server network and shared clipboard. Then execute ``//paste -a``.

**Plugins being used on the server:**

Arceon, Builders-Utilities, BungeeTabListPlus, Essentials, (WorldEdit)FastAsyncWorldEdit, goBrush, goPaint, HeadDatabase*, Hyperverse, LegendEssentials, LegendSchematicScatter, LuckPerms, Vault, VoidGenerator, VoxelSniper, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

### PR DESCRIPTION
**Pull request by aurorasmiles**
Makes clipboards multi server compatible
fixes #638

### CODE REVIEW

**Review by N0tMyFaultOG — APPROVED** [review]

**Comment by MattBDev** [comment]
I'm fine with this change but we shouldn't officially support using clipboards across multiple servers. Schematics are the better option.

**Review by MattBDev — APPROVED** [review]

**Comment by lusu007** [comment]
In my opinion cross-server clipboards are a pretty fundamental feature for mid to large building servers/networks. 
Creating a schematic each time you want to copy something to another server takes time and clutters up the schematics folder.

I think you should officially support it. But its your decision. 😄

**Comment by SirYwell** [comment]
Copying my message from discord:
> I mean disk optimized clipboards are meant to use disk space instead of memory, so using them for cross-server clipboards might be out of scope (and it's also error-prone, as multiple processes might access the files at the same time and stuff)

While cross-server clipboards might be useful, I don't think the current implementation of the DiskOptimizedClipboard should support it. If we're going to support it, we should probably look into something like [Chronocle-Map](https://github.com/OpenHFT/Chronicle-Map) or similar.

**Review by dordsor21 — APPROVED** [review]
I think that it's best to look into doing this correctly in the future, but for now it's probably fine

**Pull request merged**
