### PR TITLE
Build a Mojang mapped jar in addition to the reobf one, publish both to Modrinth with correct metadata

### PR DESCRIPTION
**Pull request by jpenilla**
## Overview
Removes the need for remapping on Paper, reducing disk usage and first-start times.

## Description
The project now builds two ShadowJars, one for Paper 1.20.5+ only (Mojmapped), and one that will work on Spigot or Paper for all versions (Spigot mapped).

We publish the Spigot jar to Modrinth twice to make sure their version selector picks the right jar for the platform regardless of the Minecraft version.

I've also added a runtime check on startup to notify the user when they have the wrong jar for their platform, tested with:
- Mojmap jar on reobf Paper 1.20.4: throws useful error as expected
- Spigot-mapped jar on mojmap Paper 1.20.4: "This FastAsyncWorldEdit version does not fully support your version of Bukkit" message, same as before this PR. Do we want to add more checks for this or should we just assume people running mojmap Paper <1.20.5 probably know what they are doing?
- Mojmap jar on mojmap Paper 1.20.4: works normally
- Mojmap jar on Paper 1.21.3: works normally
- Spigot-mapped jar on reobf Paper 1.20.4: works normally
- Spigot-mapped jar on Paper 1.21.3: works normally, logs warning as expected
- Mojmap jar on Spigot 1.21.3: throws useful error as expected (mc version is less relevant for this test)
- Spigot-mapped jar on Spigot 1.21.3: works normally (mc version is less relevant for this test)

I'm also wondering if it's intentional that 1.20.4 is not in the supported list for Modrinth publishing but 1.20.3 and 1.19.4 are. Let me know and I can adjust this if needed.

I've updated the GitHub Actions, not sure if Jenkins will need changes or not.

### Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by SirYwell — APPROVED** [review]
Looks good.

**Review by dordsor21 — APPROVED** [review]

**Comment by NotMyFault** [comment]
Caused
Screenshot 2024-11-24 at 10 47 35

https://github.com/IntellectualSites/FastAsyncWorldEdit/actions/runs/11917825188/job/33275322933#step:13:108

**Comment by jpenilla** [comment]
@NotMyFault strange, I would try using the id instead of the name: z4HZZnLr

**Comment by NotMyFault** [comment]
> @NotMyFault strange, I would try using the id instead of the name: z4HZZnLr

Thanks for the pointer, where did you get the ID from?

**Comment by jpenilla** [comment]
image
Modrinth has an option to copy the ID when clicking this icon with three dots

**Comment by NotMyFault** [comment]
Screenshot 2024-11-24 at 19 51 03

This doesn't work either.

**Pull request merged**
